In [9]:
import numpy as np

def diagonally_dominant(matrix):
    matrix = np.array(A)
    n = matrix.shape[0]
    
    for i in range(n):
        diagonal = abs(matrix[i, i])
        diagonal_sum = sum(abs(matrix[i, j]) for j in range(n) if j != i)
        
        if diagonal < diagonal_sum:
            return False
    
    return True


A = [[4, 1, 2],
     [1, 3, 1],
     [0, 1, 5]]

B = [[1, 3, 2],
     [9, 1, 6],
     [7, 8, 1]]


print("Is the matrix diagonally dominant?", diagonally_dominant(A))
print(np.array(A))

print("Is the matrix diagonally dominant?", diagonally_dominant(B))
print(np.array(B))

Is the matrix diagonally dominant? True
[[4 1 2]
 [1 3 1]
 [0 1 5]]
Is the matrix diagonally dominant? True
[[1 3 2]
 [9 1 6]
 [7 8 1]]
